avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c system/app.c -o build/system/app.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c system/audio.c -o build/system/audio.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c system/console.c -o build/system/console.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c system/fastrand.c -o build/system/fastrand.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c system/keys.c -o build/system/keys.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c system/main.c -o build/system/main.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c system/minio.c -o build/system/minio.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c system/note_freqs.c -o build/system/note_freqs.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c system/readline.c -o build/system/readline.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c system/serial.c -o build/system/serial.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c system/spi.c -o build/system/spi.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c system/tinyprintf.c -o build/system/tinyprintf.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c system/video.c -o build/system/video.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/launcher/launcher.c -o build/apps/launcher/launcher.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/forth/block.c -o build/apps/forth/block.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/forth/compile.c -o build/apps/forth/compile.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/forth/debug.c -o build/apps/forth/debug.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/forth/dict.c -o build/apps/forth/dict.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/forth/disasm.c -o build/apps/forth/disasm.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/forth/editor.c -o build/apps/forth/editor.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/forth/error_codes.c -o build/apps/forth/error_codes.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/forth/forth.c -o build/apps/forth/forth.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/forth/forth_video.c -o build/apps/forth/forth_video.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/forth/interpret.c -o build/apps/forth/interpret.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/forth/io.c -o build/apps/forth/io.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/forth/math.c -o build/apps/forth/math.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/plasma/plasma.c -o build/apps/plasma/plasma.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/slideshow/slideshow.c -o build/apps/slideshow/slideshow.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/test_bitmap_modes/test_bitmap_modes.c -o build/apps/test_bitmap_modes/test_bitmap_modes.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/test_colors/test_colors.c -o build/apps/test_colors/test_colors.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/test_keys/test_keys.c -o build/apps/test_keys/test_keys.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/test_mode_alignment/test_mode_alignment.c -o build/apps/test_mode_alignment/test_mode_alignment.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/test_patterns/test_patterns.c -o build/apps/test_patterns/test_patterns.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/test_raster_interrupts/test_raster_interrupts.c -o build/apps/test_raster_interrupts/test_raster_interrupts.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -c apps/test_text_modes/test_text_modes.c -o build/apps/test_text_modes/test_text_modes.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c system/app_launch.S -o build/system/app_launch.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c system/isrs.S -o build/system/isrs.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c system/minio_decimal.S -o build/system/minio_decimal.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c system/minio_handlers.S -o build/system/minio_handlers.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c system/randseed.S -o build/system/randseed.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c system/videomodes.S -o build/system/videomodes.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c assets/amscii_font_8x8.S -o build/assets/amscii_font_8x8.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c assets/bitspreadtable.S -o build/assets/bitspreadtable.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c assets/cosine.S -o build/assets/cosine.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c assets/crumbquadtable.S -o build/assets/crumbquadtable.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c assets/hsvtable.S -o build/assets/hsvtable.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c assets/nibbledoubletable.S -o build/assets/nibbledoubletable.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c assets/test_tileset_8x8.S -o build/assets/test_tileset_8x8.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c apps/forth/forth_mem_layout.S -o build/apps/forth/forth_mem_layout.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c apps/forth/forth_opcodes.S -o build/apps/forth/forth_opcodes.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c apps/forth/forth_opcodes_2.S -o build/apps/forth/forth_opcodes_2.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c apps/forth/forth_opcodes_3.S -o build/apps/forth/forth_opcodes_3.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c apps/forth/forth_outer_interpreter.S -o build/apps/forth/forth_outer_interpreter.o
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -x assembler-with-cpp -c apps/forth/forth_words.S -o build/apps/forth/forth_words.o
./scripts/generate-app-linker-script-overlay.sh .noinit launcher forth_serial forth plasma slideshow test_bitmap_modes test_colors test_keys	test_mode_alignment test_patterns test_raster_interrupts test_text_modes > build/app_overlays.ld
avr-gcc -g -Os -std=gnu11 -Wundef -Wall -Wextra -Wno-unused-parameter -Wno-missing-braces -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -fdata-sections -ffunction-sections -mrelax -Wa,--no-pad-sections -MMD -MP -DF_CPU=14318182	 -DSTARTUP_APP=launcher -DHW_VERSION=AMETHYST_HW_LATEST -include isr_reserved_registers.h -Iinclude -mmcu=atmega1284 -g -Wl,--undefined=_mmcu,--section-start=.mmcu=0x910000 -Wl,-Map,colorvideo.map -Wl,--gc-sections -Wl,--relax -Wl,@banned_stdlib_functions -T atmega1284_amethyst.ld -o colorvideo.elf build/system/app.o build/system/audio.o build/system/console.o build/system/fastrand.o build/system/keys.o build/system/main.o build/system/minio.o build/system/note_freqs.o build/system/readline.o build/system/serial.o build/system/spi.o build/system/tinyprintf.o build/system/video.o build/apps/launcher/launcher.o build/apps/forth/block.o build/apps/forth/compile.o build/apps/forth/debug.o build/apps/forth/dict.o build/apps/forth/disasm.o build/apps/forth/editor.o build/apps/forth/error_codes.o build/apps/forth/forth.o build/apps/forth/forth_video.o build/apps/forth/interpret.o build/apps/forth/io.o build/apps/forth/math.o build/apps/plasma/plasma.o build/apps/slideshow/slideshow.o build/apps/test_bitmap_modes/test_bitmap_modes.o build/apps/test_colors/test_colors.o build/apps/test_keys/test_keys.o build/apps/test_mode_alignment/test_mode_alignment.o build/apps/test_patterns/test_patterns.o build/apps/test_raster_interrupts/test_raster_interrupts.o build/apps/test_text_modes/test_text_modes.o build/system/app_launch.o build/system/isrs.o build/system/minio_decimal.o build/system/minio_handlers.o build/system/randseed.o build/system/videomodes.o build/assets/amscii_font_8x8.o build/assets/bitspreadtable.o build/assets/cosine.o build/assets/crumbquadtable.o build/assets/hsvtable.o build/assets/nibbledoubletable.o build/assets/test_tileset_8x8.o build/apps/forth/forth_mem_layout.o build/apps/forth/forth_opcodes.o build/apps/forth/forth_opcodes_2.o build/apps/forth/forth_opcodes_3.o build/apps/forth/forth_outer_interpreter.o build/apps/forth/forth_words.o
avr-objdump -D colorvideo.elf > colorvideo.lst
avr-size colorvideo.elf
rm -f colorvideo.hex colorvideo.eep.hex
avr-objcopy -j .text -j .data -j .app_*_data -O ihex colorvideo.elf colorvideo.hex
avrdude -c avrispmkII -P usb -p atmega1284 -U flash:w:colorvideo.hex:i
